name: Mend UA Release Scan

on:
  push:
    branches:
    - '**release**'

jobs:
  call-java-prioritize:
    uses: samq-democorp/whitesource-config/.github/workflows/java-prioritize.yml@main
    secrets: inherit